version: '3'
services:
  app:
    depends_on:
      - redis
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - fincode
    volumes:
      - .:/app:cached
      - /app/node_modules

  redis:
    image: redis:latest
    container_name: redis_finconde
    ports:
      - '6379:6379'
    networks:
      - fincode
    volumes:
      - fincode:/data

  postgres:
    image: postgres:latest
    container_name: postgres_fincode
    restart: always
    ports:
      - 5432:5432
    volumes:
      - fincode:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=fincode
      - POSTGRES_DB=fincode
    networks:
      - fincode

networks:
  fincode:
    driver: bridge

volumes:
  fincode:
